### ISSUE TITLE
Unnecessary O(n) factor in complexity of some metric catalog functions 

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap#1114]
This for loop: https://github.com/intelsdi-x/snap/blob/master/control/metrics.go#L302 has O(n^2) complexity for broad queries like `/intel/*`. Additionally there https://github.com/intelsdi-x/snap/blob/master/control/metrics.go#L337 is used the least effective method of removing element from slice. If there is no reason to keep query cache ordered `map[string]struct{}` should be used instead of `[]string`.

**Comment by IzabellaRaulin** [comment]
The operation on https://github.com/intelsdi-x/snap/blob/master/control/metrics.go#L302 does **not** take place on every collection, but only in the beginning and when metrics catalog has been changed (loading/unloading collector plugin). That minimize impact on collection process.

Moreover, there is PR #907 (on-hold) where regexp is no longer use to expand queries. Expanding this to the list of matched metrics namespaces will be based only on metricsTree. What is more, this approach will allow to specify an instance of dynamic metric.

For example, given a tree like this:
```
        root
         / \
        /   \
      foo  bar
     /\       /\
    /  \     /  \
   a    b  c    d
                  /\
                 /  \
                 e   *
                     /\
                    /  \
                   f    g
```

what `*` in the end means `Fetch()` on this tree returns all descendants of a given tree's node, in examples:

a) results of `Fetch()` on root node (`/root/* `)
   root/foo/a
   root/foo/b
   root/bar/c
   root/bar/d
   root/bar/e
   root/bar/\*/f
   root/bar/\*/g

b) results of `Fetch()` on *foo* node (`/root/foo/* `)
   root/foo/a
   root/foo/b

c) results of `Fetch()` on *bar* node (`/root/bar/* `)
   root/bar/c
   root/bar/d
   root/bar/e
   root/bar/\*/f
   root/bar/\*/g

c) result of `Fetch()` on specific instance, eg. docker container id (`/root/bar/docker_id/* `)
/root/bar/docker_id/f 
/root/bar/docker_id/g 

The same as before going through metrics tree will not take place every time when CollectMetrics() is executed, but only at the moment of:
 - creating/starting a task 
 - when metrics catalog has been changed what happens when:
    - a new collecotr plugin was loaded,
    - newer version of collector plugin was loaded,
    - or some collector plugin was unloaded.

Only tuples will stay be recognized via regular expression - see [snap:specific_dynamic_metric](https://github.com/IzabellaRaulin/snap/blob/6e9c54b3c9cd14f1844ccc78b04ca4665810abce/control/metrics.go#L269), but it is very simply regexp which is executed on a single element of namespace.

Regarding to:
> Additionally there https://github.com/intelsdi-x/snap/blob/master/control/metrics.go#L337 is used the least effective method of removing element from slice. If there is no reason to keep query cache ordered map[string]struct{} should be used instead of []string.

there will be a struct [mTree](https://github.com/IzabellaRaulin/snap/blob/6e9c54b3c9cd14f1844ccc78b04ca4665810abce/control/metrics.go#L224) which holds requested metrics and maps them to the cataloged metrics type.

@lmroz, does it cover/resolve this issue?

**Comment by lmroz** [comment]
I know when this code is executed and this PR doesn't resolve the issue. Look there: https://github.com/IzabellaRaulin/snap/blob/6e9c54b3c9cd14f1844ccc78b04ca4665810abce/control/metrics.go#L393

Again in `for` ranging over items in metric catalog there is linear duplicate search resulting in O(n^2) time. Now look where this is called:
https://github.com/IzabellaRaulin/snap/blob/6e9c54b3c9cd14f1844ccc78b04ca4665810abce/control/metrics.go#L421
https://github.com/IzabellaRaulin/snap/blob/6e9c54b3c9cd14f1844ccc78b04ca4665810abce/control/metrics.go#L480

So, for each new metric type loop over all queries then over all expansions and over all matched metric in metric catalog loop again to search duplicates. This is even worse than I was thinking, its O(n^3). If you load plugin with 1000 metrics, assuming we have just one simple query `/intel/*` that has one "expansion" that matches these 1000 metrics you are doing something that has magnitude of about 1000*1000*1000 operations.

And I'm not quite sure why we have regular expressions used during expansion. They won't work.
User can give regexp that is not matching itself, like eth(1|0) that should be expanded to eth0 and eth1 (it works on master but I'm not sure that was desired or just side effect of used method), in your code it will cause panic, because you are going to have factor 0 in number of matches and then divide by this zero (using `%`). Similar case, `eth*` in your code will cause collection over all interfaces (if plugin supports dynamic query in this position) or no collection at all (`*` is not routed to anything).

**Comment by katarzyna-z** [comment]
New way of getting metrics from metric.tree resolve that.

cc: @IzabellaRaulin
