### ISSUE TITLE
RFC: Arbitrary namespace separator

### ISSUE THREAD

**Issue by marcin-krolik** [intelsdi-x/snap#1234]
### Problem description
There are at least two collector plugins (df, swap) identified where dynamic namespace element value may contain "/" character, which breaks metrics namespace.

Problem was reported by Mirantis and is tracked in [github](https://github.com/intelsdi-x/snap-plugin-collector-df/issues/10).

Example:
```bash
Filesystem                Type     1024-blocks      Used Available Capacity Mounted on
udev                      devtmpfs     8113640        12   8113628       1% /dev
tmpfs                     tmpfs        1624944      2524   1622420       1% /run
/dev/dm-3                 ext4       103077152  84200980  13617116      87% /
none                      tmpfs         102400        32    102368       1% /run/user
/dev/mapper/data--vg-data ext4       722343000 319310640 371560244      47% /data
/dev/sda1                 ext4         1998672    393128   1484304      21% /boot
/dev/mapper/vms--vg-vms   ext4       309501952 151700240 142056896      52% /vms
```
In above example "Filesystem" is dynamic namespace element.

### Proposed solution
User is able to define custom namespace speparator in task manifest for each metric independently.
```yml
---
  workflow: 
    collect: 
      metrics: 
        /intel/mock/foo: {}
        %intel%procfs%filesystem%*%space_free: {}
```
Metrics requested in collection section would have its own separator defined as in above example. While parsing task manifest, each requested metrics would be split by first encountered character. For `/intel/mock/foo` it would be `/` and for `%intel%procfs%filesystem%*%space_free` it would be `%` 

This would require changes in:
1. `wmap.CollectWorkflowMapNode` function `GetMetrics()` to recognize metric separator and split requested metric accordingly
2. `core.Namespace` function `String()` to detect if any of its `NamespaceElement`s contains `/` character, and if so, use another character from the list of allowed separators.
3. Introduction of priority list of allowed separators in `core` package. This list would be used to provide substitutes for `/` character to allow proper display of metric. 
Example list = `{"/", "%", "#", "_", ":"}. Priority would be resolved by character position on the list. Lower index meaning higher priority.

User defined separator from task manifest would not be preserved though, as there is no need for that.

This solution should be transparent for current plugins (collectors, processors, publishers)

@intelsdi-x/snap-maintainers @obourdon @elemoine

**Comment by brharrington** [comment]
Have you considered escaping instead of changing the separator? My main objection to having different separators is the string version can no longer be used reliably when consuming the data. It probably isn't a big deal if writing a plugin, but for more ad-hoc use-cases like watching a task or viewing/processing output from the file publisher using the shell it would be cumbersome. The same metric name could be encoded in different ways or more likely related metrics would have different prefixes because of differences in the dynamic values for some namespace element.

Perhaps a related question, what is the rationale behind the current set of [disallowed characters](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md#metric-naming)? Presumably `/` was because it was being used as a separator. Is there a specific reason behind the others?

> Introduction of priority list of allowed separators in core package

For sake of argument, what if I have a namespace element using all characters from the list?

**Comment by obourdon** [comment]
Please have a look at my [further comment in the original issue](https://github.com/intelsdi-x/snap-plugin-collector-df/issues/10#issuecomment-249232094)

**Comment by jcooklin** [comment]
> what is the rationale behind the current set of disallowed characters? 

Originally the list was informed by the fact that we were using regex internally against the namespaces however this has since changed.  At this point the special characters that would need to be handled include  '/', '*', and '.'.   The plugin authoring documentation is in the process of being updated and we are planning to remove the need for special handling of `.`.

> For sake of argument, what if I have a namespace element using all characters from the list?

This begs will String() now need to return `(string, error)`?  I think that we could use the priority list of characters but if this list is exhausted we could start walking the UTF-8 character set.  This being said it's highly unlikely that a namespace would contain every item in the proposed separator list above.  

> Have you considered escaping instead of changing the separator? 

Yes,  as @obourdon stated above there has been some debate about it on issue https://github.com/intelsdi-x/snap-plugin-collector-df/issues/10.   

I'd like to capture the pros/cons of these two approaches and everyone's preference (👍 or 👎) for each.

**Comment by jcooklin** [comment]
**Arbitrary separator**:
Pros

* doesn't include escapes which may pose a problem in some deployment configurations that involve reverse proxies

Cons

* Requires a priority list of characters that would be tested when printing the string representation of a namespace
* It makes it harder to reliably parse after we have published. For example, parsing the file produced by the file publisher would need to know that it splits using the first character it reads.

**Comment by jcooklin** [comment]
**Escaping special characters when part of a namespace element**:
Pros
* standard/intuitive approach to the problem

Cons
* Results may vary if reverse proxies are involved  ([details](https://github.com/intelsdi-x/snap-plugin-collector-df/issues/10#issuecomment-228691533))

**Comment by rji** [comment]
Personally, I like the idea of an arbitrary separator, kind of like how GNU sed works:

```
$ echo "foobarbazquux" | sed 's%bar%BAR%'
fooBARbazquux
$ echo "foobarbazquux" | sed 's/bar/BAR/'
fooBARbazquux
```

**Comment by brharrington** [comment]
> kind of like how GNU sed works

The sed separator being arbitrary makes them easier to write initially and that is the common usage pattern. Very few things need to actually read and match on the sed expression itself. In my usage the metric namespaces are far more often read and used as inputs for tools like grep, sed, awk, jq, etc. Being able to use simple string operations for matching namespaces makes it much easier to do simple adhoc analysis and debugging.

For example, I think it is quite useful to be able to watch a task and easily extract a subset of metrics using basic string operations like startswith:

```
jq '.event[] | select(.namespace | startswith("/intel/procfs/iface/")) | [.timestamp, .namespace, .data] | @csv'
```

**Comment by brharrington** [comment]
> doesn't include escapes which may pose a problem in some deployment configurations that involve reverse proxies

If I understand this correctly, the concern is that `%2F`

```
/v1/metrics/intel/fs/%2Fvar%2Flog/space_free
```

Would get automatically decoded by some servers to:

```
/v1/metrics/intel/fs//var/log/space_free
```

What about something like [CSV](https://en.wikipedia.org/wiki/Comma-separated_values#Standardization) only using `/` instead of comma as the main separator? So basically you would just quote the path element:

```
/v1/metrics/intel/fs/"/var/log"/space_free
```

If a quote is used in the field, then it would need to be represented with two quote characters.

**Comment by marcin-krolik** [comment]
> What about something like CSV only using / instead of comma as the main separator?

@brharrington I was thinking about the same and we discussed it internally before, but it was not chosen. I still think that standard escaping like `%2F` or even letting plugin user define it in plugin config (`df` and `swap` collectors) would be much straight forward and would not require any changes in framework.

**Comment by candysmurf** [comment]
Thanks for your contribution. It seems that I need to work on this task. Apparently, there are tradeoffs.
What's the verdict?

I have a couple of questions:
1. Will a namespace have different separators? if your answer is yes, would you please give a use case? E.g.
```
  /a%b/c%d
```
2. Will a plugin have mixed namespaces?

Thank you in advance for your help!

**Comment by candysmurf** [comment]
Here are my thoughts:

* Priority list sounds a good idea. We only support a list of valid separators. 
* If a namespace contains all characters of the valid separators, core.Separator will be used.
* If a namespace does not contain any character of the valid separators, the first one in the valid separator list will be used and so on.
* if a namespace contains characters other than following, alphabet, digits, and characters defined in the valid separator list, error out.

Proposed Valid separator list:

"/", "-", "_", "~"

**Comment by candysmurf** [comment]
PR #1252 is ready for your review. It supports arbitrary separators.
