### ISSUE TITLE
Too verbose, too much unnecessary data, some intenal logic re-work

### ISSUE THREAD

**Issue by evilezh** [intelsdi-x/snap#1300]
Each metric today have a bunch of parameters which repeats in each metric. 
timestamp, tags, version, last_advertised ...  unit in most cases is useless as you know what you are processing and how data is represented and unit seems always is the same if it is B .. then B .. it is not changing to KB MB or anything else. Also many plugins even do not set that field at all.

Another thing is about namespace definitions. e.g. /abc/qwe/asd/static/static  and in same time /abc/qwe/asd/< dynamic >/static, which leads to two issues:
1. possible collisions
2. harder to parse/categorize 

As I understand, design comes from use cases, where you send single metric with all tags to receiver (e.g. influxdb). But how to effectively process data via kafka/elasticsearch/stream processors ... ??
You get messages 50+kb (in case of json).. every 10 seconds from every single server and most of data is just repeating timestamps, tags etc. 

How i currently process data:
- Read timestamp,tags.. from first message
- tokenize namespace for each message, group and build tree structure
- process know static elements, assume that remaining is dynamic elements
  after processing data is ~10% of original data amount.
1. I suggest to move to tree at top level and have general methods to write data/metrics using path in tree. (imagine mkdir -p /path1/path2/path3 and put file in there (metric) ). Underlying can be map[string]interface{} or some kind of tree node structs. And main level function putMetric(path,data). No namespace creation boiler code ... simple and effective.
2. Have strict rules about making namespace, which avoids any possible collision between static and non-static elements. 
3. allow regex in path elements

All that would reduce amount of data (in case of json), simplifies logic to process data, avoid possible collisions. 

If that makes all makes sense, I could go through current code and outline in more precise details or suggest exact implementation  ...

**Comment by kindermoumoute** [comment]
> Each metric today have a bunch of parameters which repeats in each metric. 
timestamp, tags, version, last_advertised ... unit in most cases is useless as you know what you are processing and how data is represented and unit seems always is the same if it is B .. then B .. it is not changing to KB MB or anything else. Also many plugins even do not set that field at all.

Are you referring to this [metric structure](https://github.com/intelsdi-x/snap-plugin-lib-go/blob/master/v1/plugin/metric.go#L30-L42) we use in the plugin workflow? Is your suggestion to reduce this structure?

> Another thing is about namespace definitions. e.g. /abc/qwe/asd/static/static and in same time /abc/qwe/asd//static, which leads to two issues:
1. possible collisions
2. harder to parse/categorize

Totally agree, this kind of namespace display an error "too ambiguous" since #1220.

**Comment by jcooklin** [comment]
>But how to effectively process data via kafka/elasticsearch/stream processors ... ??
You get messages 50+kb (in case of json).. every 10 seconds from every single server and most of data is just repeating timestamps, tags etc.

**Comment by jcooklin** [comment]
>But how to effectively process data via kafka/elasticsearch/stream processors ... ??
You get messages 50+kb (in case of json).. every 10 seconds from every single server and most of data is just repeating timestamps, tags etc.

The publisher can choose, as appropriate, how and what to publish.  So depending on what you are publishing to it might make sense to filter static or unchanging data. 

> I could go through current code and outline in more precise details or suggest exact implementation

I'd like to hear more about your suggestions.  Specifically I'm curious to understand how it would impact the protobuf [plugin.proto](https://github.com/intelsdi-x/snap/blob/master/control/plugin/rpc/plugin.proto) definition which is used.

**Comment by evilezh** [comment]
Good :)
I'll try to keep as close to existing idea as possible ... but it might be useful to change it in core.
I havn't yet familiarized myself with code, so some of things might be already in way I'm describing. I just want to put my version.

Let's assume plugin have id defined like:
/vendor/name1/name2/version
or maybe just /name/version e.g. /snap-collector-cpu/8
So main rule UNIQUE ID + VERSION. 

Let's assume task something like like (yeah .. full regex):
```json
[  
   {  
      "plugin":"/plugin-1/.*",
      "metrics":[".*?/cpu.*"]
   },
   {  
      "plugin":"/plugin-2/1",
      "metrics": ["/procs/.*","/data/exact"]
   }
]
```
Then we run each plugin matching regex. Or we might assume exact match ... those are details.

Then each plugin collects own tree of metrics.
Which means we would have single metrics message: 
with few fields like timestamp, tags etc. and map<object,object> (not sure how to express exactly) or just simple byte array of serialized json object.

I have not investigated all use cases .. and i might miss reason for bringing them ..
int64 Version = 2;  // for what .. we know version of plugin already ??? 
ConfigMap Config = 3; // it is enough at top level to bypass any config
Time LastAdvertisedTime = 4; // ?? 
map<string, string> Tags = 5; // top level enough
Time Timestamp = 6; // top level enough
string Unit = 7; //  we can read plugin documentation and we know what units it will send
string Description = 8; //  who cares ? read plugin documentation

Having in mind this - 
inside plugin to store metric: 
if (path matches any metrics_regex[]) -> write_metrics(tree, path,data) 
with simple recursive function you can implement creating missing nodes in path and write data in final object)  + you test path against metrics[] regexes.
From tree it also cost nothing to reconstruct full path (/asd/asd/asd/asd) back (as some output plugins probably would like to). 

You say goodbye to .isDynamic (who cares .. we have regex). You do not need all that namespace duplication (some plugins like mesos mess up with it :) and it forgets to create new namespace objects and keep rewriting same object many times).
forget about pre-generating namaspaces for writing then matching metrics to put or not inside etc.
You can write metric as you read anywhere in tree .. if it matches regex.

p.s. 
If you need to send some exact data type or want to keep extra information about value ... then rather than adding value at the end you can do:
```json
"load_avg_5min" : { 
    "value" : 0.32,
    "data_type" : "float"
    "metric_type" : "gauge"
}
```
or to avoid duplication plugin could return schema object with meta information, rather than repeating that information again and again.

Summary:
Have more effective internal representation of data, more flexible selection of metrics we want to see, simplified plugin coding (plugin). Having tree structure would require proper planing to avoid any possible collisions ( no more static and dynamic elements in same slot). 

I think with some optimization there and here some ideas from #1226 it could make really good project.  I'll fix some modules which I use and does not work properly (as for today: mesos - not properly created namespaces for dynamic objects, processes - collisions and few improvements). 

p.s.
Here is another idea -  which might be easier to implement on top of existing. 
1. Introduce different data formats for storing metrics. So - plugin can store either supported one.
2. create methods to transform from one format to another. e.g. if collector uses format v2 .. and output wants v1. 

As for serialization - you can always have byte[] :)

**Comment by kindermoumoute** [comment]
> I have not investigated all use cases .. and i might miss reason for bringing them ..
int64 Version = 2; // for what .. we know version of plugin already ??? 
ConfigMap Config = 3; // it is enough at top level to bypass any config
Time LastAdvertisedTime = 4; // ?? 
map Tags = 5; // top level enough
Time Timestamp = 6; // top level enough
string Unit = 7; // we can read plugin documentation and we know what units it will send
string Description = 8; // who cares ? read plugin documentation

I don't know reason for metric version (2), unit (7) and description (8) to be in the workflow of collect/process/publish. We use those when listing metrics (e.g. `snapctl metric list`), so we could get them from `GetMetricTypes` in collector plugins.

Config (3), tags (5) and timestamp (6) can't be done at the top level, for different reasons:
* Config is essential if you want to customize the workflow on a metric only. e.g.
```
{
  ...
  "workflow": {
    "collect": {
      "metrics": {
        "/intel/mock/foo": {
          "config": {
             "host": "google.com"
        }
      }
...
```
* For the reason we can customize metric workflow, tags need to be unique to a metric.
* Timestamp is different from a metric to another. Even if the difference is really small on some fast collectors, using a top level timestamp would introduce a significant error when task are running at high frequency. 

`LastAdvertisedTime` (4), I don't know why it's there too. :-)

**Comment by evilezh** [comment]
Let's see .. 
I guess most of collectors do not use those features. I understand - you want bypass parameters to metric and for that purpose use config. 
Two types of metrics:
- simple ... when you have `"metric":value`
- complex ... when you have `"metric":{ "value": value, "timestamp":123123123,"tags":[],"config":"google.com"}` 
I think - "simple" we will match most of plugins.


As for timestamp :)Don't we talk about nanoseconds ? In all my practice, i never collected data at nanosecond resolution ... If I run collection every 10 seconds .. then i do not care much .. it which fraction 10 second interval  data will be collected as I will round up anyway. Same with 1 second resolution.

Tags per metric.

As per plugins and namespaces .. we can assume, that plugin might have more that one namespace/id .. and each of then might own configuration. 

And few words about configuration. It is very bad practice to put kafka/mesos/etc. plugin configuration into global, which requires snapd reload. we have dynamic plugins, dynamic tasks .. but configuration is static. I think such practice should be denied and plugins should receive configuration only and only from task.

**Comment by IRCody** [comment]
@evilezh: I tried to address your feedback below. If I missed something let me know.

```
Each metric today have a bunch of parameters which repeats in each metric. 
timestamp, tags, version, last_advertised
```
Is it not possible to make these different for each metric? I guess you could argue that version would be for all metrics in a plugin (but I don't know that are current implementation requires that).

```
 ... unit in most cases is useless as you know what you are processing and how data is represented and unit seems always is the same if it is B .. then B .. it is not changing to KB MB or anything else. Also many plugins even do not set that field at all.
```
The unit could change and it's not hard imagine a processor/publisher that uses unit in a way that isn't tied to a specific collector plugin. i.e. I publish different metrics (from a variety of plugins) to a database, I publish the unit also so that the data isn't tied to some plugins implementation and instead can stand by itself.

```
Another thing is about namespace definitions. e.g. /abc/qwe/asd/static/static and in same time /abc/qwe/asd/< dynamic >/static, which leads to two issues:
1. possible collisions
2. harder to parse/categorize
```
Is your critique that this is harder on the framework or on plugin authors?
```
As I understand, design comes from use cases, where you send single metric with all tags to receiver (e.g. influxdb). But how to effectively process data via kafka/elasticsearch/stream processors ... ??
You get messages 50+kb (in case of json).. every 10 seconds from every single server and most of data is just repeating timestamps, tags etc.
```
I don't understand what you're saying here. Where does json come in?

```
How i currently process data:

Read timestamp,tags.. from first message
tokenize namespace for each message, group and build tree structure
process know static elements, assume that remaining is dynamic elements
after processing data is ~10% of original data amount.
```
Do you have code you could link to? How did you arrive at your ~10% number? What assumptions are you making about the data?

```
I suggest to move to tree at top level and have general methods to write data/metrics using path in tree. (imagine mkdir -p /path1/path2/path3 and put file in there (metric) ). Underlying can be map[string]interface{} or some kind of tree node structs. And main level function putMetric(path,data). No namespace creation boiler code ... simple and effective.
Have strict rules about making namespace, which avoids any possible collision between static and non-static elements.
allow regex in path elements
All that would reduce amount of data (in case of json), simplifies logic to process data, avoid possible collisions.

If that makes all makes sense, I could go through current code and outline in more precise details or suggest exact implementation ...
```

It doesn't make sense to me. Are you talking bout metric storage in Snap or in plugins? In plugins, authors are free to store however they wish. I'm also not clear on what the reference to json means as Snap isn't using json to send/receive metrics? I feel like maybe there is a specific case you're trying to optimize for. If so, I think it would be easier to understand these suggestions in context.

```
Good :)
I'll try to keep as close to existing idea as possible ... but it might be useful to change it in core.
I havn't yet familiarized myself with code, so some of things might be already in way I'm describing. I just want to put my version.

Let's assume plugin have id defined like:
/vendor/name1/name2/version
or maybe just /name/version e.g. /snap-collector-cpu/8
So main rule UNIQUE ID + VERSION.

Let's assume task something like like (yeah .. full regex):

[  
   {  
      "plugin":"/plugin-1/.*",
      "metrics":[".*?/cpu.*"]
   },
   {  
      "plugin":"/plugin-2/1",
      "metrics": ["/procs/.*","/data/exact"]
   }
]
Then we run each plugin matching regex. Or we might assume exact match ... those are details.

Then each plugin collects own tree of metrics.
Which means we would have single metrics message: 
with few fields like timestamp, tags etc. and map (not sure how to express exactly) or just simple byte array of serialized json object.
```
Is you're idea that we would send this tree of metrics through to processors/publishers?

```
I have not investigated all use cases .. and i might miss reason for bringing them ..
int64 Version = 2; // for what .. we know version of plugin already ???
ConfigMap Config = 3; // it is enough at top level to bypass any config
Time LastAdvertisedTime = 4; // ?? 
map Tags = 5; // top level enough
Time Timestamp = 6; // top level enough
string Unit = 7; // we can read plugin documentation and we know what units it will send
string Description = 8; // who cares ? read plugin documentation
```
@kindermoumoute already addressed some of these. So I'll address the ones he wasn't sure about. 
(2) - We can have multiple versions of a metric going through snap at the same time. Version can be specified in the task manifest.
(4) - Don't have a strong argument for including this. I imagine it was included to map directly to core.Metric.
(7) - I think I made a case for Unit above.
(8) - Have mixed feelings about this. I don't directly see a strong use-case for this in the plugins but maybe there is one that deals with publishing data and provides a description that gives similar utility as what Unit provides? I'll have to think about it more.

```
Having in mind this - 
inside plugin to store metric: 
if (path matches any metrics_regex[]) -> write_metrics(tree, path,data) 
with simple recursive function you can implement creating missing nodes in path and write data in final object) + you test path against metrics[] regexes.
From tree it also cost nothing to reconstruct full path (/asd/asd/asd/asd) back (as some output plugins probably would like to).
```
Applying regexes across the entire path doesn't seem like you gain anything from being in a Tree. If you're still forced to iterate on all metrics you gain nothing. I think you could even argue you lose something because of increased complexity.

```
You say goodbye to .isDynamic (who cares .. we have regex). You do not need all that namespace duplication (some plugins like mesos mess up with it :) and it forgets to create new namespace objects and keep rewriting same object many times).
forget about pre-generating namaspaces for writing then matching metrics to put or not inside etc.
You can write metric as you read anywhere in tree .. if it matches regex.
```
This doesn't make sense to me.

```
p.s. 
If you need to send some exact data type or want to keep extra information about value ... then rather than adding value at the end you can do:

"load_avg_5min" : { 
    "value" : 0.32,
    "data_type" : "float",
    "metric_type" : "gauge"
}
or to avoid duplication plugin could return schema object with meta information, rather than repeating that information again and again.
```
What do you mean by adding value at the end? How do you envision schema's working? would Snap then be providing some sort of validation that the data coming out matches the schema? Do plugins downstream need to know about the schema?

```
Summary:
Have more effective internal representation of data, more flexible selection of metrics we want to see, simplified plugin coding (plugin). Having tree structure would require proper planing to avoid any possible collisions ( no more static and dynamic elements in same slot).
```
A theme throughout my questions, but when you say internal do you mean to Snap or to the plugins? Internally Snap stores the metric catalog as a Tree already. Once a workflow starts the metrics are passed around through each step in the workflow as they were received by snap from the previous step.

```
p.s.
Here is another idea - which might be easier to implement on top of existing. 
1. Introduce different data formats for storing metrics. So - plugin can store either supported one.
```
Plugins can store data however they want. Plugins only need to be able to accept/respond in the format Snap expects. How it's dealt with internally is entirely up to the Plugin author.
```
2. create methods to transform from one format to another. e.g. if collector uses format v2 .. and output wants v1.
```
I think this is a slipper slope of complexity. How many formats do you support?
```
As for serialization - you can always have byte[] :)
```
[]byte's of what?

**Comment by evilezh** [comment]
> Is it not possible to make these different for each metric? I guess you could argue that version would be for all metrics in a plugin (but I don't know that are current implementation requires that).
Of course it is and probably it would be also possible to enrich with even more data every single unit, but who really needs it ? Ok, even it is required - can't that all be optional ?

Units: 
I would say - it is rather normal use case and requirement send data in same units. Otherwise you can't display that data without normalization of inputs (which is forced extra processing). 

> Is your critique that this is harder on the framework or on plugin authors?

I do not know - will snap collector accept it,  but you can write into any namespace with your plugin and plugins itself sometimes write static and dynamic fields in same slot.

> Do you have code you could link to? How did you arrive at your ~10% number? What assumptions are you making about the data?
I think some visual representation could help understand better.
I'm putting data to tree and removing all fields, except value. Here is what i get at the end of post-processing:
```json
{
  "intel": {
    "procfs": {
      "processes": {
        "parked": 0,
        "waking": 0,
        "wakekil": 0
      },
      "cpu": {
        "cpu-total": {
          "system": 0,
          "stolen": 0
        },
        "0": {
          "system": 0,
          "stolen": 0
        }
      }
    }
  },
  "_meta": {
    "timestamp": 0,
    "tags": {}
  }
}
```
If we talk about ideas ... 
First 3 /intel/tamtam/asdasd is not necessary and better do not allow plugins to write into that. Plugin must have unique ID and it shouldn't send along with metric it's again and again.
Here is how it would look, if we remove first 3 parts of tokens and assing single value:
```json
{
  "plugin-processes": {
    "parked": 0,
    "waking": 0,
    "wakekil": 0
  },
  "plugin-cpu": {
    "cpu-total": {
      "system": 0,
      "stolen": 0
    },
    "0": {
      "system": 0,
      "stolen": 0
    }
  },
  "_meta": {
    "timestamp": 0,
    "tags": {}
  }
}
```
If we go on and extend it .. including possible tags per metric and other extra info (as for version number - it can be played out many different way ... just one of it):
```json
{
  "plugin-processes:7": {
    "_meta": {
      "plugin_started_timestamp": 0,
      "tags": {}
    },
    "parked": 0,
    "waking": 0,
    "wakekil": 0
  },
  "plugin-cpu:3": {
    "_meta": {
      "plugin_started_timestamp": 0,
      "tags": {}
    },
    "cpu-total": {
      "system": 0,
      "stolen": {
        "value": 0,
        "unit": "ticks",
        "tags": {},
        "description": "tick-tock",
        "timestamp": 123123123
      }
    },
    "0": {
      "system": 0,
      "stolen": 0
    }
  },
  "_meta": {
    "collection_run_timestamp": 0,
    "tags": {}
  }
}
```
As per enforcing and having schema ... You have documentation for it. Or you write plugin which follows some rules and it works, or you don't.  You can't stop me doing silly things if i want to (e.g. currently i think i'm free to overwrite other plugins data). 

As for regex. Question is at which point you apply. 
if we have function:  `putMetrics(tree, "/intel/procfs/processes/parked",0)`
Then we can test it before calling it ... does `"/intel/procfs/processes/parked"` matches any regex .. if yes - then write.

About functions:
To make life easier for plugin writers to be in line with format, i suggested to have library of functions, which would properly write collected metrics in format we need.
So . .you have class MetricTree which plugins must use. Then you have generic methods implemented which reads/writes to them. And at the end you send that MetricTree object (how it is serialized does not matter ). If plugins "MUST" use it, then they MUST use also functions around it. And functions will come from your main (this) library, which will ensure data integrity in way it is required, that should answer this:
> What do you mean by adding value at the end? How do you envision schema's working? would Snap then be providing some sort of validation that the data coming out matches the schema? Do plugins downstream need to know about the schema?

And having all data in tree like format wold also allow to apply extra attributes at any point for subtree etc. which at the end should lead to much more flexibility, rather than plain array or Metrics.

**Comment by evilezh** [comment]
p.s. ignore my last comment mostly. 
I need to spend some time to go through code. There is tree :) and just need to think about few adjustments maybe.

**Comment by lynxbat** [comment]
> Each metric today have a bunch of parameters which repeats in each metric.

I believe your use case influences your perception here. There is absolutely nothing wrong with that. But, some of your proposed changes to abstractions may introduce a tradeoff for other use cases.

You perceive the data points a repetition because your implementation is sophisticated enough to not need these data points per metric. Also, it is likely the subset of metrics you are collecting are somewhat uniform.

Repetition is a pattern recognized over a specific set of data. The purpose of Snap is to expose open ended telemetry and our current struct here is intended to support a wide array of current and future types of metrics. Just because you see a repetition in your use case does not mean that this is ubiquitous to all of them (though it is possible).

Our goal is to leverage the abstractions in processor and publisher plugins to decouple and handle these implementation-specific use cases. We only want to drive changes higher in the the catalog, collection plugins, or the workflow types if they support this decoupling.

> Another thing is about namespace definitions. e.g. /abc/qwe/asd/static/static and in same time /abc/qwe/asd/< dynamic >/static, which leads to two issues:

I was not aware we allowed namespace collisions on static vs. dynamic and I would consider this a design problem also.

> As I understand, design comes from use cases, where you send single metric with all tags to receiver (e.g. influxdb). But how to effectively process data via kafka/elasticsearch/stream processors ... ??
You get messages 50+kb (in case of json).. every 10 seconds from every single server and most of data is just repeating timestamps, tags etc."

This is key. As you point out, stream processing has different use cases that time series databases. I am making the assumption that your JSON reference here is for messages dropped onto a message bus from a Snap publisher.

I am also assuming the reason the tags and timestamps are redundant to you after the first message is because your implementation:

- knows the interval (10 secs) and infers the delta between received messages
- or is using the message timestamp as metric timestamp for when it was dropped into the bus
- you store the tags once as your use case considers them immutable

There are two points here for me.

#### First, your statement that there is repetition is accurate. If portions of the metric are immutable or not used either sending once or never is an optimization.

#### Second, your use case directly applies to the reason why the processor and publisher domains exist. Your issue is summarized as: you need to be able to optimize the sinking of data from Snap into your stream processing system.

However, I have couple key things to point out on why this is not ubiquitous to all use cases:

- Tags will not always be immutable for every use case. This means for some use cases sending every time or on changes have to be supported. Tags are not always redundant. They are redundant to your implementation.
- Timestamps are very important for many use cases. In your case the timestamp is less useful because you are inferring the delta between events in some form or your analytic goal does not include time as a data point. Snap’s current timestamp is meant to be as accurate as possible when the plugin itself collects a metric. Not when it is received from the plugin, not when it is given to a publisher, and not when it is atomically written to a database or message bus. Some use cases do not need this level of accuracy like yours. But that does not mean we drop that ability for everyone.

> process know static elements, assume that remaining is dynamic elements
after processing data is ~10% of original data amount."

I am not following exactly the implementation here but I can make an assumption on the pattern.

You have the ability to reduce the data down quite a bit and still meet your goal. And you are suggesting this operation can be moved into Snap.

That is awesome and exactly the reason why the processor plugin exists. If your reduction ability is per node (as this pattern cannot work cross-node inside Snap) you can implement the reduction inline with a processor and reduce before you publish to your message bus.

The ability to leverage the processor domain to do this allows you to optimize for your use case. But other use cases have other goals where that reduction may not apply. Having a processor that does this would be amazing and I would suggest this is a great place to start.

> All that would reduce amount of data (in case of json), simplifies logic to process data, avoid possible collisions."

Yes, for you use case I 100% agree.

My recommendation is:

- Explore the code on the publisher you are using and see if you can implement optional configuration changes to allow the filtering of fields before dropping a message. In my head a simple `filter-field` key with a delimited list of the fields to filter would suffice. The `send once` problem is harder since it requires Snap to maintain state around if the field has been sent before. Because of the nature of Snap this is not trivial. I would recommend a frequency knob on fields for this problem. Something like send every N number of messages. If a plugin restarts it would just send it again if it did not have an active count. This is slightly less efficient depending on plugin stability.
- Look into moving you data reduction for static & dynamic metrics into a processor. If you are able to make a decision inline on what is interesting on a node’s set of metrics, a processor can reduce that inside Snap before you sink through your publisher.

I think your suggestions around how to optimize for this use case are sound. I also think they couple well with our plugin model. I do not believe they work well for changing things behind the plugin abstractions.

**Comment by candysmurf** [comment]
@evilezh, the beauty of supporting both static and dynamic metrics is that you can query lots metrics by using dynamic metric definition and query as little as a few metrics by using static metrics. Of course, some measurements only have the static metrics.

If your issue is to identify your target metrics among all of the received metrics I have a sample implementation to show your around. 

Do you mind to ping me on Slack, we can work it out. At the mean time, may we close this issue?

**Comment by jcooklin** [comment]
Closing this issue as it has been moved to [slack](https://intelsdi-x.herokuapp.com/).
