### ISSUE TITLE
Snap Jolokia collector plugin

### ISSUE THREAD

**Issue by akantak** [intelsdi-x/snap#1342]
Hey, 
I would like to use Snap but I would need to have Jolokia collector plugin for my Java/JMX applications.

Also it would be useful for Scala applications when using [library for Jolokia for SBT](https://github.com/jtescher/sbt-jolokia)

Thanks!

**Comment by mjbrender** [comment]
Great call @akantak! I was talking with @jtlisi about his use of Jolokia and that being a great target for collection. A few questions as someone who's never used it: 

* Is there a set of metrics that are more important than others for monitoring Java/JMX apps? 
* Is there a set of metrics that we should ignore/not collect? 
* Is there a good example application you'd recommend spinning up to test the plugin?

**Comment by khrisrichardson** [comment]
@mjbrender The table on page 5 of http://web.swcdn.net/creative/pdf/techtips/1309_SAM_Best_Practices_For_Monitoring_JMX.pdf doesn't look like an unreasonable starting point.

Latency, throughput, and queue length tend to suffice, with error rates thrown in for good measure.

Here's an implementation to cross-reference: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia

Also here are some details regarding how to integrate jolokia with Cassandra for example: https://github.com/chrusty/telegraf-cassandra#the-solution

**Comment by karol-brejna-i** [comment]
In our case we have one Jolokia per app/pod (in contrast to having one Jolokia working with many JMX endpoints) so in initial attempt we were able to make some simplifications.

Our base idea for plugin is:
- the plugin accepts a list of working Jolokia endpoints in dedicated section of snap config 
- on start, the plugin retrieves JMX metrics available on these endpoints; the metrics catalogue is updated based on that
- task config can hold one (or more) Jolokia endpoints to read the metrics from and the list of metrics it's interested in

This approach has the following consequences:
- when the plugin starts, it requires that there is some Jolokia endpoint working
- metrics catalog is updated once (because of the plugin lifecycle) - if there are new endpoints used in tasks, metrics they can handle is restricted to this list
(which means even if the new endpoints introduce new metrics, they cannot be served -- unless you change the global config and restart SNAP) 

@akantak has already some working version of this. We'll share soon ;-)

**Comment by nanliu** [comment]
@karol-brejna-i that sounds great, love to see what you guys have built.

**Comment by akantak** [comment]
https://github.com/intelsdi-x/snap-plugin-collector-jolokia

please share your ideas/opinions

**Comment by mjbrender** [comment]
@akantak so cool! I'll bring this up today and see who has time to run through it. 

Curious - have you run this in any test or prod configurations? If so, I'd love to hear about the setup. cc @jtlisi

**Comment by akantak** [comment]
@mjbrender not yet, we had tested it on [this](https://jolokia.org/tutorial.html) on host, and with this app in docker image

**Comment by kjlyon** [comment]
@akantak, you rock! Thank you for raising this issue and then going above and beyond to contribute a Snap collector plugin for Jolokia! 

To make your plugin even better, check out our tips in [PLUGIN_AUTHORING](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md). In there it explains how to get your plugin listed in our [Plugin Catalog](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md) and the requirements for appropriate [plugin statuses](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_STATUS.md). Since the plugin exists now I am going to close this issue and take Jolokia off the plugin wishlist. 

Thank you again for your contributions!
