### ISSUE TITLE
Linux Mint install

### ISSUE THREAD

**Issue by IvanMenshykov** [intelsdi-x/snap#1417]
I have a problem with install package.
Because I have Linux Mint and to `/etc/apt/sources.list.d/intelsdi-x_snap.list` was add next link:
```
deb https://packagecloud.io/intelsdi-x/snap/linuxmint/ rosa main
deb-src https://packagecloud.io/intelsdi-x/snap/linuxmint/ rosa main
```
And I have to edit link for install package:
```
deb https://packagecloud.io/intelsdi-x/snap/ubuntu/ trusty main
deb-src https://packagecloud.io/intelsdi-x/snap/ubuntu/ trusty main
```

**Comment by nanliu** [comment]
Looking at Linux Mint, it appears to be compatible with Ubuntu, but it isn't a platform we test against.

I'm assuming repo.list below the result of running the package cloud repo scripts? (i.e. the command ` curl -s https://packagecloud.io/install/repositories/intelsdi-x/snap/script.deb.sh | sudo bash`)
```
deb https://packagecloud.io/intelsdi-x/snap/linuxmint/ rosa main
deb-src https://packagecloud.io/intelsdi-x/snap/linuxmint/ rosa main
```

Based on the [packagecloud documentation](https://packagecloud.io/intelsdi-x/snap/install), I think you'll have to over ride the OS detection, so perhaps this would solve it:
` curl -s https://packagecloud.io/install/repositories/intelsdi-x/snap/script.deb.sh | os=ubuntu dist=trusty sudo bash`

Depending on whether your sudoer config strips environment variable, this may or might not work. It might be easier to simply cat the appropriate repo settings instead of using the setup script since Mint isn't officially supported by Packagecloud setup scripts.

**Comment by IvanMenshykov** [comment]
Yes, Linux Mint compatible with Ubuntu. 

For me work this (Linux Mint 17):
`curl -s https://packagecloud.io/install/repositories/intelsdi-x/snap/script.deb.sh | sudo os=ubuntu dist=trusty bash`

For Linux Mint 18:
`curl -s https://packagecloud.io/install/repositories/intelsdi-x/snap/script.deb.sh | sudo os=ubuntu dist=xenial bash`

[Here](https://www.linuxmint.com/download_all.php) we can see package base for Linux Mint.

**Comment by mjbrender** [comment]
To confirm, did Snap install okay after you followed these steps @IvanMenshykov? Either way, let's think about where to document overrides like this for new users @nanliu 👍

**Comment by IvanMenshykov** [comment]
@mjbrender, Yes, everything ok :+1: :computer:

**Comment by mjbrender** [comment]
Awesome, plus a PR? 😍 You're the best @IvanMenshykov!
