### ISSUE TITLE
Snap plugin thread safety during initialization of plugins

### ISSUE THREAD

**Issue by nanliu** [intelsdi-x/snap#1449]
We have several plugins with pending issues related to thread safety during initialization of plugins. Several of them have been addressed. Here's a list to track them centrally:

- [x] https://github.com/intelsdi-x/snap-plugin-collector-cpu/issues/38
- [x] https://github.com/intelsdi-x/snap-plugin-collector-disk/issues/21
- [x] https://github.com/intelsdi-x/snap-plugin-collector-df/issues/19
- [x] https://github.com/intelsdi-x/snap-plugin-collector-interface/issues/16
- [x] https://github.com/intelsdi-x/snap-plugin-collector-load/issues/13
- [x] https://github.com/intelsdi-x/snap-plugin-collector-meminfo/issues/23
- [x] https://github.com/intelsdi-x/snap-plugin-collector-processes/issues/23
- [x] https://github.com/intelsdi-x/snap-plugin-collector-swap/issues/11

**Comment by lmroz** [comment]
This list might be not valid, because most (if not all) of these plugins use ConcurrencyCount = 1. Some are using this value from very beginning, but for some that was added during development, even for smart https://github.com/intelsdi-x/snap-plugin-collector-smart/commit/63ee15e4a49e35c9ac6fa1d594a7e8bb28c2dcc2#diff-65647fbc09fddf28c78c248603ed1656L45
This commit sets ConcurrencyCount to 1 which makes the issue I reported originally perhaps inexistent (I haven't expected that plugin's Meta changed).

That's of course if there is no way that single workflow will make overlapping `CollectMetrics` call, but I don't know if there any circumstances that might happen.

Moreover, I've seen code of some of these plugins (i.e. processes) and there is no issue regardless of ConcurrencyCount value, because no struct variables (changed during callback) exists.

**Comment by IzabellaRaulin** [comment]
This plugin uses **sticky routing strategy**, so concurrency count is set to 1, what means there is no possibilities to use a single plugin instance by two or more tasks. 

Based on above, I will close this issue. Of course, please do not hesitate to re-open if you notice that this issue is still valid in some circumstances. Thank You.
