### ISSUE TITLE
failed_count more then the hit_count ?

### ISSUE THREAD

**Issue by fengw084** [intelsdi-x/snap#1662]
Running the task, and occasionally there will be several failed_count more then the hit_count, this is BUG or normal？

**Comment by kjlyon** [comment]
Hi @fengw084 , thank you for bringing this up! I would like to dig deeper into this, do you mind sharing your task manifest with me to see if I can reproduce the error?

**Comment by mbbroberg** [comment]
I also wonder if you're asking for clear definitions. I believe it goes that: 
* `hit_count` is the number of times a workflow ran successfully 
* `failed_count` is the number of times a workflow failed to run

Making it so that `hit_count` + `failed_count` = total attempts to run workflow. 

FWIW, I don't believe that this relationship is clear.

**Comment by kjlyon** [comment]
Hi @fengw084, it's been a while since we have heard from you. I hope @mbbroberg and I were able to resolve your question. Please open another issue or contact us on [our Slack channel](https://intelsdi-x.herokuapp.com/) if you have more questions, we would be happy to help!
