### ISSUE TITLE
Defining process for releasing plugins

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#661]
It seems that the latest release packages for snap (https://github.com/intelsdi-x/snap/releases/tag/v0.10.0-beta) don't contain binaries for the plugins - talking especially about plugins listed in PLUGIN_CATALOG in section "Maintained plugins".

So maybe we should decide on how we are going do deliver plugins binaries to end users. I'm assuming we want to distribute binaries for usability reasons - not everyone would be interested in preparing development environment in order to build a plugin.

Maybe as part of PLUGIN_AUTHORING we should define plugins release process, detailing for example:
1. How to deliver plugins binaries:
   1. as part of snap release package
   2. **individually per plugin**
2. When to create new release:
   1. **After each plugin version update** (mandatory)
   2. **After each snap version update** (strongly recommended)
3. Binaries format:
   1. **Linux**
   2. **Darwin**
4. Packaging format:
   1. **tar.gz**
   2. **zip**
5. Who:
   1. **snap maintainers team** (secondarily)
   2. **plugin author** (primarily)

My proposal in bold.

**Comment by sandlbn** [comment]
@andrzej-k :Do we have any plans for night builds ? or ppa and yum repositories for snap and key plugins ?

**Comment by mjbrender** [comment]
We should firm this up and get it in docs.

**Comment by mjbrender** [comment]
We've had a lot of progress on this since launch. The map to all builds starts with http://snap.ci.snap-telemetry.io/ and looking at that XML output gives you a map to all available plugins through this build process. 

Example: `plugins/snap-plugin-collector-bind/master/1c068b54c2e48ca6cfdd32bee85fd6c6a0ad91d5/linux/x86_64/snap-plugin-collector-bind` is in there, which means I can download it: 

```
$ wget http://snap.ci.snap-telemetry.io/plugins/snap-plugin-collector-bind/master/1c068b54c2e48ca6cfdd32bee85fd6c6a0ad91d5/linux/x86_64/snap-plugin-collector-bind
``` 

These builds stick to the format of: 

```
http://snap.ci.snap-telemetry.io/plugins/<plugin_name>/<sha1>/<os>/<arch>/<plugin_name>
http://snap.ci.snap-telemetry.io/plugins/<plugin_name>/latest_build/<os>/<arch>/<plugin_name>
```

More information will be added to the CONTRIBUTING.md file in an upcoming PR.

**Comment by kindermoumoute** [comment]
Most of that proposal is solved with [pluginsync](https://github.com/intelsdi-x/snap-pluginsync), there is still some discussion about packaging on https://github.com/intelsdi-x/snap/issues/1276
