### ISSUE TITLE
Get tribe/agreements is called when just issue snapctl

### ISSUE THREAD

**Issue by mingchan** [intelsdi-x/snap#721]
It is more of a question. 
When running snapctl without any command and noticed that "get tribe/agreements" is issued from snapctl.

Is there a particular use-case for that?

I'm using " v0.10.0-beta-2-g5da30c0"

On the snapd side, the follow message is shown.

INFO[0816] API response                                  _module=_mgmt-rest index=49 method=GET status=Not Found status-code=404 url=/v1/tribe/agreements

**Comment by danielscottt** [comment]
Hi @mingchan,

@IRCody and I were just talking about this.  `snapctl` checks whether or not the target `snapd` instance is in tribe mode by first checking if `/v1/tribe/agreements` is a valid path.  If the request returns without error, `snapctl` will show additional flags / subcommands which are specific to tribe.  If a `404` is returned from the `/v1/tribe/agreements` request, then those flags are hidden, because tribe is not enabled on this `snapd` instance.

However, the _order_ of operations here is not ideal; the request should only be made when the top-level help is invoked (`--help`, `-h`, or `len(os.Args) == 1`).  Cody is working on something that will fix this right now.

**Comment by mingchan** [comment]
Got it. 
Also why not explicitly call into the snapd to get the information instead of inferring it? 
A new API call like "GET /v1/snapinfo", which perhaps can return more info than just if it is in tribe mode?

**Comment by lynxbat** [comment]
@mingchan. Solid idea. Would you mind writing a spec for it?

**Comment by mingchan** [comment]
Will give a try.
