### ISSUE TITLE
Tag all metrics collected in a workflow via config

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#827]
As a user I would like to be able to apply a configuration to a task or a global configuration that will apply a tag to any metric that is collected.  This would would allow additional context to be communicated through to the metrics final destination(s) providing insights like what experiment, user, group, etc this task was associated to.

**Comment by lynxbat** [comment]
Should we rename this to something other than tag? To me this feel more like a `label`.

Are other decoration implementations different enough to name this something different or prefix it?
When you say global configuration, you mean all tasks from that service? What happens with global config is in tribe?

**Comment by marcin-krolik** [comment]
Hi, 
I would like to implement tagging mechanism as it was requested by Athena and GSA team. I prepared draft of design and implementation. Let me know what you think.

## Tagging metrics
As a user I want to apply global metric meta data persistent throughout snapd lifetime, 
so that it will be available at publish endpoint.

As a user I want to apply local metric meta data persistent throughout task lifetime, 
so that it will be available at publish endpoint.

### Tagging through global config
To achieve persistence of metric meta data throughout snapd lifetime, additional configuration to global config is required. It can be implemented as new tag section included in "scheduler" part of global configuration.

```json
	"control": {},
    "scheduler": {
        "work_manager_queue_size": 10,
        "work_manager_pool_size": 2,
		"tags": {
			"foo": "foo_val",
			"bar": "bar_val"
		}
    },
	"restapi": {},
	"tribe": {}
```

When snapd is being started and global configuration is read, scheduler tags section would be transported to scheduler module. This would require extending scheduler by new field to store "global tags".

```go
type scheduler struct {
	workManager     *workManager
	metricManager   managesMetrics
	tasks           		*taskCollection
	state           		schedulerState
	eventManager    *gomit.EventController
	taskWatcherColl *taskWatcherCollection
	globalTags 		map[string]string
}
```

When task is being started "global tags" would be merged into tasks' workflow under "global" key in map composition (tree). This would require extending workflow by new field to store tags.

```go
type schedulerWorkflow struct {
	state 				WorkflowState
	// Metrics to collect
	metrics 				[]core.RequestedMetric
	// The config data tree for collectors
	configTree   		*cdata.ConfigDataTree
	processNodes 	[]*processNode
	publishNodes 	[]*publishNode
	// workflowMap used to generate this workflow
	workflowMap  	*wmap.WorkflowMap
	eventEmitter 	gomit.Emitter
	tags         			map[string]map[string]string
}
```

When workflow is being started all tags under "global" key in map composition would be applied on metrics **after** collect job is finished on each and every metric returned from collection job.

For example if user defines global tags as 

```json
	"tags": {
		"foo": "foo_val",
		"bar": "bar_val"
	}
```

it would result in all metrics collected with running instance of snapd would be tagged with ```foo: foo_val``` and ```bar: bar_val```

### Tagging through task manifest
To achieve persistence of metric meta data throughout task lifetime, additional section in task is required. It can be implemented as new tag sub-section under "collect", similar to "config" sub-section.

```json
{
    "collect": {
        "metrics": {
            "/intel/foo/bar": {},
            "/intel/foo/baz": {}
        },
        "config": {},
        "tags": {
            "/intel/foo/bar": {
                "tag1": "val1",
                "tag2": "val2"
            },
            "/intel/foo": {
                "tag3": "val3"
            }
        },
        "process": [],
		"publish": []
```

When workflow is being created task manifest tags would be included in workflow under map composition (tree). 
When workflow is being started all workflow tags would be applied on metrics from the leaves of the tags main keys **after** collect job is finished.

For example, a task collects ```/intel/foo/bar``` and ```/intel/foo/baz``` with tags being specified as :

```json
"tags": {
	"/intel/foo/bar": {
		"tag1": "val1",
		"tag2": "val2"
	},
	"/intel/foo": {
		"tag3": "val3"
}
```

it would result in metric ```/intel/foo/bar``` being tagged with ```tag1: val1```, ```tag2: val2``` and ```tags: val3``` while ```/intel/foo/baz``` only with ```tag3: val3```.

### Strategy for adding tags:
1. Apply all workflow tags from  "global" branch
2. If tag key is already available in metric tags, overwrite its value (user defined global tags have priority over collectors hard coded tags)
3. Apply all workflow tags from other branches
4. If tag key is already available/applied in metric tags, overwrite its value (user defined task tags have priority over collectors hard coded tags and global tags)

**Comment by jcooklin** [comment]
>When workflow is being started all tags under "global" key in map composition would be applied on metrics after collect job

I would consider integrating more of the behavior in control.CollectMetrics.  The workflow should communicate tags, that may have been set in the task definition, to control (CollectMetrics) where we merge them with tags that may have been defined globally.      

To this end I feel the following steps would be required.

1. Add tags field (map[string]string) to CollectWorkflowMapNode
1. Add tags field (map[string]string) to schedulerWorkflow
1. Add tags field (map[string]string) to collectorJob
1. Set schedulerWorkflow.tags in convertCollectionNode
1. Add tags to newCollectorJob func (and set the tags field)
1. Add tags, that we now have on CollectorJob, to the metric that we construct in collectorJob.Run and send to control.CollectMetrics
1. In control.CollectMetrics merge tags from global config before collecting metrics

*The above doesn’t mention adding tags to the global config but that will need to also be done.  While the easiest thing to do would be to add a tags section under Control.Config I’m of the opinion that belong as a top level configuration item.

**Comment by ppalucki** [comment]
from perspective of user I would like see "Strategy" more with declarative description ("global config has higher priority than defaults") rather imperative "set this if not set this in struct X" (I don't exactly understand what collectorJob) - that would help understand the intention better

example "precedence rules" [here](http://pythonhosted.org/configglue/topics/environment-variables.html#environment-variables-during-command-line-integration)

IMO the precedence rules should follow "time ordering" like this:

1. tags compiled in collector ("hardcoded in plugin default values") - build time
2. tags from config file - moment of preparing a config file (ops decision), before deply
3. values provided to snapd at start (command line) - snapd deamon starting moment  (or something from ENV)
4. values returned by `PluginCollector.GetMetricTypes` - after plugin is uploaded, building schema time (more dynamic) - can be see in metricCatalog
5. tags from task.json - task creation time (but task no yet run, scheduled later)
6. tags set in `PluginCollector.Collect`  - metric collection phase at the begining of task, 
7. tags set by order of processors in task definition `Processor.Process` - run after "collecting metrics phase", before passing to Publisher

The rationale behind this, that if tag represents something volative/"likely to change", the last moment in time to set value should win ("last write wins" strategy), just because is most up to date.

I don't exactly get that from Strategy and Joel response, but maybe it says the same :)

**Comment by marcin-krolik** [comment]
@jcooklin @ppalucki thanks for the input!

**Comment by jcooklin** [comment]
Tags provided in the task should override those provided in the global config which override those on the cataloged plugin.

**Comment by candysmurf** [comment]
Will we run into a situation where multiple tasks collect the same metric but they have specified different tags? Should we build the capability to distinguish them?

let us be clear on the precedence(low to high by the number). Correct them if you disagree.
1. hardcoded inside program
2. global config
3. task config
4. command line

**Comment by IRCody** [comment]
>Will we run into a situation where multiple tasks collect the same metric but they have specified different tags? Should we build the capability to distinguish them?

I don't think collecting the same metric with different tags would cause any issues. The task are run independently. I don't see how they would conflict. Can you expand on where you think the issue might be?

**Comment by candysmurf** [comment]
@IRCody, I don't think it could cause the issue. I would like to mention this aspect so that we have the capability to distinguish the same metric with different tags by various tasks.

**Comment by candysmurf** [comment]
@IRCody, I think we should go into more detail with the examples for merging between the global config and task config for multiple tasks running the same metric.

**Comment by ppalucki** [comment]
@jcooklin said:
> Tags provided in the task should override those provided in the global config which override those on the cataloged plugin.

so how this relates to "Collecting" phase?

1. tags created/updated during Collect will be overridden by tags set in global or task config ? 
2. are tags set in global config available (for unknown reason) in `Collect(input []metrics)` input but those set in "task" not ? (IMO we shouldn't to not give opportunity to use that tags by plugin author in inappropriate way - collector should relay on config rather than tags)

so the resulting flow is like this, right ?
```



                         +------------------------------------------+
                         | snapd framework                          |
                         |                                          |
                         |   +----------------+    +-------------+  |
         +-------------------+ global config  |    | task config |  |
         |               |   +----------------+    +-------------+  |
         |               |                                     |    |
         |               +------------------------------------------+
         |                                                     |
         |                                                     |static tags
         |                                                     |
         |      query         +------------+                   |
         |    +--------------->            | dynamic tags      v        tags
         |      tags          | collector  +--------------> override +------------------>
         +-------------------->            |
                              +------------+
```
a little unexpected* (just for me), that tag value set during task definition (upload task) overrides this provided dynamically (fresher) value - but thx to @marcin-krolik can see rationale behind this
"whatever user specifies during interacting with snapd (global config/task config) should win over hardcoded logic in collector plugin, even when it is more up to date)" 

and this solves problem with tag values provided with pattern "/intel/* -> foo:bar - no need to merge

ps. *unexpected for case, when there is long running tasks and user set value at the very early, and then after plugin update I could get updated value from collector (rather than default from config)
