### ISSUE TITLE
It seems that CollectMetrics method in PluginControl has an unnecessary argument

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap#852]
It seems that CollectMetrics method in PluginControl has an unnecessary argument, deadline time.Time is not used in CollectMetrics method, see: https://github.com/intelsdi-x/snap/blob/master/control/control.go#L900. Am I right?

**Comment by IRCody** [comment]
You are right that it is not used. I am not sure of the history behind it though. Any thoughts @intelsdi-x/snap-maintainers?

**Comment by jcooklin** [comment]
The deadline is currently being used in the scheduler so that jobs aren't started if the deadline has already passed ([here](https://github.com/intelsdi-x/snap/blob/master/scheduler/worker.go#L51-L56)).  The intent was to also use the deadline to trigger cancellation of the RPC call which would need to be done in the proxies for collect, process and publish.  

Labeling as "bug".

Relates to #965

**Comment by marcin-krolik** [comment]
Fixed with #1109
