### ISSUE TITLE
Pool eligibility incorrectly calculated for concurrency count > 1

### ISSUE THREAD

**Issue by marcin-krolik** [intelsdi-x/snap#910]
Function ```pool.Eligible()``` does not work properly for cases where ```p.concurrencyCount > 1``` 

Main condition:

```go
should := p.SubscriptionCount() / p.concurrencyCount
if should > p.Count() && should <= p.max {
    return true
}
return false
```
Let's assume maximum pool size to 3 and only one instance of available plugin in the pool 
```go
p.max = 3
p.Count() = 1
``` 
then

|p.SubscriptionCount()|p.concurrencyCount|should|Eligible|Expected|
| :------: |:------:| :------:| :------: | :------: |
| 1 | 2 | 0 |False | False |
| 2 | 2 | 1 |False | False |
| 3 | 2 | 1 |False | True |
| 4 | 2 | 2 |False | True |
| 5 | 2 | 2 |False | True |
| 6 | 2 | 3 |True | True |

Suggested solution:

```go
should := p.SubscriptionCount() > p.concurrencyCount * p.Count()
oversized := p.SubscriptionCount() > p.concurrencyCount * p.max
if should  && !oversized {
    return true
}
return false
```

**Comment by marcin-krolik** [comment]
@jcooklin @tiffanyfj @IRCod please take a look at this issue

**Comment by IRCody** [comment]
>```go
should := p.SubscriptionCount() > p.concurrencyCount * p.Count()
oversized := p.SubscriptionCount() > p.concurrencyCount * p.max
if should  && !oversized {
    return true
}
return false
```

I agree it seems like this doesn't follow what I would think of as valid behavior. I'm not sure that the code you put as a solution follows what I would think the valid behavior would be either. I think Eligible() is intended to be used to answer "Are we able to add another plugin to this pool?".  It looks to me like the snippet above is answering "Can we add another subscription to this pool?" (because oversized will be true based on subscriptionCount going up instead of pluginCount). The way it's used in the examples I can find are -- 
* Add a subscription
* Call Eligible() to see if I need/am able to add another plugin to this pool now that the # of subscriptions has grown.

I would say that this pool is eligible as long as:
* p.SubscriptionCount() > p.concurrencyCount * p.Count()
* number of plugins in the pool (p.Count()) is < p.max. 

I think this snippet captures that.

```go
eligible := p.SubscriptionCount() > p.concurrencyCount * p.Count()
// Check if pool is eligible and number of plugins is less than maximum allowed
if eligible && p.Count() < p.max{
    return true
}
return false
```

For examples of Eligible() calls see: [runner.go](https://github.com/intelsdi-x/snap/blob/master/control/runner.go#L339), [control.go](https://github.com/intelsdi-x/snap/blob/master/control/control.go#L656).

**Comment by marcin-krolik** [comment]
You're right, thanks @IRCody for pointing that out.

**Comment by marcin-krolik** [comment]
PR #917 ready for review
