### ISSUE TITLE
Task should not be created if deadline is lower than task interval

### ISSUE THREAD

**Issue by PatrykMatyjasek** [intelsdi-x/snap#960]
AFAIK task interval is also timeout for CollectMetrics. It is possible to set deadline for whole task as a lower value than interval. And if metrics collection took more time than deadline but less than collection interval task is failing on publishing. 
Snapctl should not create task with deadline lower than interval, and put user information that deadline is too short.

**Comment by IRCody** [comment]
Seeing #852, is deadline actually used?

**Comment by lynxbat** [comment]
Deadline should be used. If it is not then it needs to be reversed. Deadline prevents runaway queueing to workers.

**Comment by jcooklin** [comment]
>Deadline should be used. If it is not then it needs to be reversed. Deadline prevents runaway queueing to workers.
Today the deadline is used as @lynxbat describes above.  There was an intent to also cancel RPC calls when the deadline was exceeded which has not been completed and is captured in #852.

**Comment by marcin-krolik** [comment]
Task interval is not used as timeout for CollectMetrics call. `DefaultClientTimeout` which is currently hard coded to 10s, timeouts client connection. Task deadline and task interval do not interfere, since deadline means other jobs (process, publish) will not be executed, while intervals means how often task will spin.
