### ISSUE TITLE
Agent initiated control-path

### ISSUE THREAD

**Issue by msundara** [intelsdi-x/snap#993]
Usecase: 
I want to host a snap controller app in a public cloud to manage a geographically distributed set of physical and virtual servers that are behind firewalls that prevents outside-in communication. I can't use snapctl because it is outside-in communication.

Possible approaches:
(1) Snapd could be configured to periodically initiate a connection to a configured 'controller' and check for 'things to do'. Things to do are instructions to do all the things that can be done via snapctl. This is simple but could be difficult to use because it doesn't support an interactive programming model. It would be basically listing all the commands in a format that will be interpreted by the agent, which will then reach back to the controller to get plugins, task definitions etc.
(2) Snapd could be configured to periodically initiate a connection to a configured controller and it opens up a bi-directional websocket channel over which request/response for multiple commands could happen. This would be convenient as it allows for error handling logic and offers the same semantics as using snapctl in an outside-in model. Maybe snapctl could take a parameter to a controller and running it with that option will cause it to 'wait' for the agent to connect to the controller, at which point snapctl can issue requests and get responses until it issues a 'done' command which causes the agent to close the connection,
(3) We could write a snapd proxy that can support outside-in communication and route commands to different agents behind it, but this may be prohibited due to security policies of network.
(4) Do nothing. This is a deployment issue that the user has to solve.

**Comment by woodsaj** [comment]
This is an important feature for our use case where we have many snapd instances isolated from each other (eg behind NAT'ed connections) that we want to centrally manage.

We have discussed this internally within our team and have a few ideas.

Ideally we would like to just be able to use Tribe, with a single tribe member reachable by all tribe members acting as a "master" node. 
However the use of github.com/hashicorp/memberlist is the primary blocker as it only works when all nodes can communicate to each other, which is not the case when using NAT'ed connections.  Though adding support for pluggable transport protocols as mentioned in https://github.com/hashicorp/memberlist/issues/21 would go a long way in helping by allowing all members to be able to connect to the "master", it would not solve the problem of all other members not being able to connect to each other, which i understand is neccessary for memberlist to work correctly.

The next best option is similar to (3) where we simply add a reverse client so that when a node starts up it connects to an "api master" via a websocket or other transport and waits for api commands to be sent.  The apiMaster would then just need to support existing api methods that could be directed at connected nodes. eg http://api.master/<node name>/v1/tasks, plus some additional methods for listing connected nodes and performing aggregated commands

**Comment by woodsaj** [comment]
@msundara i have put together a working POC of an agent initiated transport for the REST client.

In short, the snap agent makes a connection to a websocket server.  This server then uses the native Snap client library to control the agent.

see https://github.com/woodsaj/snap/pull/1

**Comment by woodsaj** [comment]
@msundara I have thrown together a quick demo screencast of the POC.
https://vimeo.com/178631074

I am interested to hear if you think this is worth exploring more.

**Comment by bjray** [comment]
@woodsaj , @msundara - thanks for putting this together.  We'll take a look and respond to you early next week.

**Comment by IRCody** [comment]
@woodsaj, @msundara:

After watching the demo we think it's definitely worth exploring. There are a few things we would like to get your opinion on. 

* How do we handle a connection interruption between snapd and the proxy server? We were thinking that snapd could periodically retry connecting, maybe with a back off but would be interested to know your thoughts.

* How do you think security of the connection should be handled?

* Setting a unique identifier for the node is important. Using something besides hostname/ip probably makes sense since you can't guarantee uniqueness on those if operating in multiple networks. 

* Sending some sort of keep alive message down the socket to ensure the connection is not closed.

* The server implementation seems like it would exists as a separate repo since there could be multiple implementations, do you agree?

Thanks for this. Sorry it took us a little bit to get back with you.

**Comment by woodsaj** [comment]
* yes, a websocket implementation will typically automatically reconnect.  The websocket protocol has specific message types for heartbeats (PIngFrame, PongFrame), but the "golang.org/x/net/websocket" requires you to implement the heartbeats yourself.  Other websocket libraries like the popular "github.com/gorilla/websocket", do provide better support.  As "github.com/gorilla/websocket.Conn" does not implement the io.ReadWriteCloser interface it is more difficult to use with JsonRPC, which is why i didn't use it for this POC.

* I think basic Auth should be sufficient.  The user:pass can be separate config items or just included in the ws_server config item. eg ws://user:pass@proxy-server/ws

* I agree that a unique identifier is important.  This POC just uses the cfg.Tribe.Name

* I also agree that the server should be in a separate repo.

**Comment by jcooklin** [comment]
@woodsaj what are the next steps for this?

Do you plan to 
* open a PR against snap adding the support for websockets?
* create a separate repo to contain your implementation of the proxy?

Would you like help? if so, what can we do to assist?

**Comment by woodsaj** [comment]
Yes I am willing able to submit a PR  and a produce a reference implementation of the server components
